import { STATUS_PROGRESS } from './constants';
import { calculateDuration, formatDate, parseDate } from './date';
import type { SnapshotPayload, Project, Task, Person } from './types';

export function toNumber(value: unknown): number {
  if (value == null || value === '') return 0;
  const num = Number(String(value).replace(/,/g, ''));
  return Number.isFinite(num) ? num : 0;
}

const DEFAULT_NOTIFICATION_SETTINGS = {
  開始日: true,
  期限前日: true,
  期限当日: true,
  超過: true,
};

function normalizeTask(raw: any, index: number): Task {
  const projectId = String(raw.projectId ?? raw.ProjectID ?? '').trim();
  const startCandidate = raw.start ?? raw['予定開始日'] ?? raw['実績開始日'];
  const endCandidate = raw.end ?? raw['期限'] ?? raw['実績完了日'];
  const start = formatDate(startCandidate);
  const end = formatDate(endCandidate);
  const estimate = toNumber(raw['工数見積(h)']);
  const actual = toNumber(raw['工数実績(h)']);

  let progress: number;
  if (estimate > 0 && actual >= 0) {
    progress = Math.min(1, Math.max(0, actual / estimate));
  } else {
    const rawProgress = raw.progress ?? raw['進捗率'];
    if (rawProgress != null && rawProgress !== '') {
      const numeric = typeof rawProgress === 'number' ? rawProgress : Number(String(rawProgress).replace(/,/g, ''));
      if (Number.isFinite(numeric)) {
        const normalized = numeric > 1 && numeric <= 100 ? numeric / 100 : numeric;
        progress = Math.min(1, Math.max(0, normalized));
      } else {
        progress = STATUS_PROGRESS[String(raw['ステータス'])] ?? 0;
      }
    } else {
      progress = STATUS_PROGRESS[String(raw['ステータス'])] ?? 0;
    }
  }
  if ((STATUS_PROGRESS[String(raw['ステータス'])] ?? 0) === 1 && progress < 1) {
    progress = 1;
  }

  const idFromPayload = raw.id ?? raw.TaskID;
  const fallbackId = `T${String(index + 1).padStart(3, '0')}`;
  const finalId = String(idFromPayload || fallbackId);

  const assignee = raw.assignee ?? raw['担当者'] ?? '';
  const assigneeEmailRaw = raw['担当者メール'] ?? raw.assigneeEmail;
  const assigneeEmail = typeof assigneeEmailRaw === 'string' ? assigneeEmailRaw.trim() : '';

  const rawDependencies = raw['依存タスク'];
  const dependencies = Array.isArray(rawDependencies)
    ? rawDependencies
        .map((value: unknown) => (typeof value === 'string' ? value.trim() : ''))
        .filter((value: string) => value.length > 0)
    : undefined;

  const notificationsRaw = raw['通知設定'] ?? {};
  const notifications = {
    開始日: notificationsRaw?.['開始日'] ?? DEFAULT_NOTIFICATION_SETTINGS.開始日,
    期限前日: notificationsRaw?.['期限前日'] ?? DEFAULT_NOTIFICATION_SETTINGS.期限前日,
    期限当日: notificationsRaw?.['期限当日'] ?? DEFAULT_NOTIFICATION_SETTINGS.期限当日,
    超過: notificationsRaw?.['超過'] ?? DEFAULT_NOTIFICATION_SETTINGS.超過,
  };

  const calendarEventIdRaw = raw['カレンダーイベントID'] ?? raw['calendarEventId'];
  const calendarEventId = typeof calendarEventIdRaw === 'string'
    ? calendarEventIdRaw.trim() || null
    : calendarEventIdRaw ?? null;

  return {
    id: finalId,
    TaskID: finalId,
    projectId,
    ProjectID: projectId,
    type: raw.type || 'task',
    parentId: raw.parentId ?? null,
    タスク名: raw['タスク名'] ?? raw.name ?? '',
    タスク種別: raw['タスク種別'] ?? '',
    担当者: raw['担当者'] ?? '',
    assignee,
    担当者メール: assigneeEmail || undefined,
    優先度: raw['優先度'] ?? '',
    ステータス: raw['ステータス'] ?? '',
    予定開始日: start,
    期限: end,
    実績開始日: formatDate(raw['実績開始日']),
    実績完了日: formatDate(raw['実績完了日']),
    ['工数見積(h)']: estimate,
    ['工数実績(h)']: actual,
    '依頼元': raw['依頼元'] ?? raw['依頼元/連絡先'] ?? '',
    '依存タスク': dependencies,
    'カレンダーイベントID': calendarEventId,
    '通知設定': notifications,
    マイルストーン: raw['マイルストーン'] ?? raw['milestone'],
    milestone: raw['マイルストーン'] ?? raw['milestone'],
    start,
    end,
    duration_days: calculateDuration(start, end),
    progress,
    createdAt: raw.createdAt,
    updatedAt: raw.updatedAt,
  };
}

function normalizeProjectStatus(status: string | undefined | null): string {
  if (!status) return '';
  // 「完了（引渡し済）」は「完了」に統一
  if (status === '完了（引渡し済）') return '完了';
  return status;
}

function normalizeProject(raw: any): Project {
  const location = raw['所在地/現地'] ?? raw['所在地_現地'] ?? '';
  const sanitizedLocation = raw['所在地_現地'];

  return {
    id: String(raw.id ?? raw.ProjectID ?? raw.projectId ?? ''),
    物件名: raw['物件名'] ?? '',
    クライアント: raw['クライアント'] ?? '',
    LS担当者: raw['LS担当者'] ?? '',
    自社PM: raw['自社PM'] ?? '',
    ステータス: normalizeProjectStatus(raw['ステータス']),
    優先度: raw['優先度'] ?? '',
    開始日: formatDate(raw['開始日']),
    予定完了日: formatDate(raw['予定完了日']),
    現地調査日: formatDate(raw['現地調査日']),
    着工日: formatDate(raw['着工日']),
    竣工予定日: formatDate(raw['竣工予定日']),
    引渡し予定日: formatDate(raw['引渡し予定日']),
    '所在地/現地': location,
    ...(sanitizedLocation !== undefined ? { '所在地_現地': sanitizedLocation } : location ? { '所在地_現地': location } : {}),
    'フォルダURL': raw['フォルダURL'] ?? '',
    '備考': raw['備考'] ?? '',
    施工費: raw['施工費'] != null ? toNumber(raw['施工費']) : undefined,
    memberNames: Array.isArray(raw.memberNames) ? raw.memberNames.filter(Boolean) : undefined,
    memberNamesUpdatedAt: raw.memberNamesUpdatedAt,
    createdAt: raw.createdAt,
    updatedAt: raw.updatedAt,
  };
}

function normalizePeople(raw: any, index: number): Person {
  const rawDailyHours = raw['稼働時間/日(h)'];
  const dailyHours = rawDailyHours == null || rawDailyHours === '' ? undefined : toNumber(rawDailyHours);

  const idFromPayload = raw.id;
  const fallbackId = `PERSON${String(index + 1).padStart(3, '0')}`;
  const finalId = String(idFromPayload || fallbackId);

  const rawType = typeof raw.type === 'string' ? raw.type.trim() : undefined;
  const normalizedType: Person['type'] | undefined =
    rawType === 'client' ? 'client' : rawType === 'person' ? 'person' : undefined;

  return {
    id: finalId,
    ...(normalizedType ? { type: normalizedType } : {}),
    氏名: raw['氏名'],
    役割: raw['役割'] ?? '',
    部署: raw['部署'] ?? '',
    メール: raw['メール'] ?? '',
    電話: raw['電話'] ?? '',
    '稼働時間/日(h)': dailyHours,
    createdAt: raw.createdAt,
    updatedAt: raw.updatedAt,
  };
}

export function computeProjectAggregates(projects: Project[], tasks: Task[]): Project[] {
  const byProject: Record<string, Task[]> = {};
  tasks.forEach((task) => {
    if (!task.projectId) return;
    if (!byProject[task.projectId]) byProject[task.projectId] = [];
    byProject[task.projectId].push(task);
  });

  return projects.map((project) => {
    const list = byProject[project.id] ?? [];
    if (!list.length) return project;
    let totalEstimate = 0;
    let weighted = 0;
    let minStart: Date | null = null;
    let maxEnd: Date | null = null;

    list.forEach((task) => {
      const estimate = toNumber(task['工数見積(h)']);
      const progress = task.progress ?? STATUS_PROGRESS[task.ステータス] ?? 0;
      totalEstimate += estimate;
      weighted += estimate > 0 ? estimate * progress : progress;

      const start = parseDate(task.start);
      const end = parseDate(task.end ?? task.期限);
      if (start) minStart = !minStart || start < minStart ? start : minStart;
      if (end) maxEnd = !maxEnd || end > maxEnd ? end : maxEnd;
    });

    const progressAggregate = totalEstimate > 0 ? weighted / totalEstimate : weighted / list.length;

    return {
      ...project,
      progressAggregate: Math.min(1, Math.max(0, progressAggregate || 0)),
      span: {
        start: formatDate(minStart ?? project.開始日),
        end: formatDate(maxEnd ?? project.予定完了日),
      },
    };
  });
}

export function normalizeSnapshot(payload: SnapshotPayload): SnapshotPayload {
  const projects = (payload.projects ?? []).map(normalizeProject);
  const tasks = (payload.tasks ?? []).map(normalizeTask);
  const people = (payload.people ?? []).map((raw, index) => normalizePeople(raw, index));
  const enrichedProjects = computeProjectAggregates(projects, tasks);
  return {
    generated_at: payload.generated_at,
    projects: enrichedProjects,
    tasks,
    people,
  };
}

export const SAMPLE_SNAPSHOT: SnapshotPayload = {
  generated_at: '2025-10-04 15:19:48',
  projects: [
    {
      id: 'P-0001',
      物件名: 'LS_新宿南口 店舗新装',
      クライアント: 'LS',
      LS担当者: '鈴木 花子',
      自社PM: '櫻本 聖成',
      ステータス: '設計中',
      優先度: '高',
      開始日: '2025-08-22',
      予定完了日: '2025-10-06',
      現地調査日: '2025-08-25',
      着工日: '2025-09-15',
      竣工予定日: '2025-10-01',
      引渡し予定日: '2025-10-06',
      '所在地/現地': '新宿区',
    },
    {
      id: 'P-0002',
      物件名: 'ABC_渋谷センター街 カフェ改装',
      クライアント: 'ABC Corp',
      LS担当者: '田中 太郎',
      自社PM: '山田 次郎',
      ステータス: '施工中',
      優先度: '高',
      開始日: '2025-09-01',
      予定完了日: '2025-11-15',
      現地調査日: '2025-09-05',
      着工日: '2025-09-20',
      竣工予定日: '2025-11-10',
      引渡し予定日: '2025-11-15',
      '所在地/現地': '渋谷区',
    },
    {
      id: 'P-0003',
      物件名: 'XYZ_池袋東口 オフィス新装',
      クライアント: 'XYZ Holdings',
      LS担当者: '佐藤 美咲',
      自社PM: '高橋 健一',
      ステータス: '企画中',
      優先度: '中',
      開始日: '2025-09-15',
      予定完了日: '2025-12-20',
      現地調査日: '2025-09-18',
      着工日: '2025-10-15',
      竣工予定日: '2025-12-15',
      引渡し予定日: '2025-12-20',
      '所在地/現地': '豊島区',
    },
    {
      id: 'P-0004',
      物件名: 'DEF_横浜みなとみらい 店舗新装',
      クライアント: 'DEF Inc',
      LS担当者: '伊藤 恵',
      自社PM: '櫻本 聖成',
      ステータス: '設計中',
      優先度: '低',
      開始日: '2025-10-01',
      予定完了日: '2026-01-31',
      現地調査日: '2025-10-05',
      着工日: '2025-11-01',
      竣工予定日: '2026-01-25',
      引渡し予定日: '2026-01-31',
      '所在地/現地': '横浜市',
    },
    {
      id: 'P-0005',
      物件名: 'GHI_品川駅前 複合施設',
      クライアント: 'GHI Group',
      LS担当者: '渡辺 直樹',
      自社PM: '中村',
      ステータス: '施工中',
      優先度: '高',
      開始日: '2025-08-01',
      予定完了日: '2025-10-31',
      現地調査日: '2025-08-05',
      着工日: '2025-08-20',
      竣工予定日: '2025-10-25',
      引渡し予定日: '2025-10-31',
      '所在地/現地': '品川区',
    },
    {
      id: 'P-0006',
      物件名: 'JKL_上野駅前 飲食店改装',
      クライアント: 'JKL Foods',
      LS担当者: '木村 健太',
      自社PM: '櫻本 聖成',
      ステータス: '設計中',
      優先度: '高',
      開始日: '2025-09-10',
      予定完了日: '2025-11-30',
      現地調査日: '2025-09-12',
      着工日: '2025-10-01',
      竣工予定日: '2025-11-25',
      引渡し予定日: '2025-11-30',
      '所在地/現地': '台東区',
    },
    {
      id: 'P-0007',
      物件名: 'MNO_六本木ヒルズ オフィス移転',
      クライアント: 'MNO Tech',
      LS担当者: '森田 優子',
      自社PM: '山田 次郎',
      ステータス: '企画中',
      優先度: '中',
      開始日: '2025-10-01',
      予定完了日: '2026-02-28',
      現地調査日: '2025-10-05',
      着工日: '2025-11-15',
      竣工予定日: '2026-02-20',
      引渡し予定日: '2026-02-28',
      '所在地/現地': '港区',
    },
    {
      id: 'P-0008',
      物件名: 'PQR_銀座中央通り ブティック新装',
      クライアント: 'PQR Fashion',
      LS担当者: '小林 真理',
      自社PM: '高橋 健一',
      ステータス: '施工中',
      優先度: '高',
      開始日: '2025-08-15',
      予定完了日: '2025-10-15',
      現地調査日: '2025-08-18',
      着工日: '2025-09-01',
      竣工予定日: '2025-10-10',
      引渡し予定日: '2025-10-15',
      '所在地/現地': '中央区',
    },
    {
      id: 'P-0009',
      物件名: 'STU_恵比寿ガーデン クリニック',
      クライアント: 'STU Medical',
      LS担当者: '加藤 誠',
      自社PM: '中村',
      ステータス: '設計中',
      優先度: '中',
      開始日: '2025-09-20',
      予定完了日: '2025-12-31',
      現地調査日: '2025-09-22',
      着工日: '2025-10-20',
      竣工予定日: '2025-12-25',
      引渡し予定日: '2025-12-31',
      '所在地/現地': '渋谷区',
    },
    {
      id: 'P-0010',
      物件名: 'VWX_秋葉原駅前 ゲームセンター',
      クライアント: 'VWX Entertainment',
      LS担当者: '斉藤 大輔',
      自社PM: '櫻本 聖成',
      ステータス: '企画中',
      優先度: '低',
      開始日: '2025-10-15',
      予定完了日: '2026-03-31',
      現地調査日: '2025-10-18',
      着工日: '2025-12-01',
      竣工予定日: '2026-03-25',
      引渡し予定日: '2026-03-31',
      '所在地/現地': '千代田区',
    },
  ],
  tasks: [
    // P-0001 タスク
    {
      id: 'T001',
      projectId: 'P-0001',
      タスク名: '基本設計_レイアウト案',
      タスク種別: '設計',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-01',
      期限: '2025-09-08',
      ['工数見積(h)']: 16,
      ['工数実績(h)']: 10,
      '依頼元': 'LS',
      start: '2025-09-01',
      end: '2025-09-08',
      duration_days: 7,
      progress: 0.625,
    },
    {
      id: 'T002',
      projectId: 'P-0001',
      タスク名: '設備レイアウト調整',
      タスク種別: '設備',
      担当者: '中村',
      assignee: '中村',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-09-05',
      期限: '2025-09-12',
      ['工数見積(h)']: 12,
      ['工数実績(h)']: 0,
      依頼元: 'LS',
      start: '2025-09-05',
      end: '2025-09-12',
      duration_days: 7,
      progress: 0,
    },
    {
      id: 'T003',
      projectId: 'P-0001',
      タスク名: '電気設備設計',
      タスク種別: '設備',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-09-10',
      期限: '2025-09-18',
      ['工数見積(h)']: 20,
      ['工数実績(h)']: 0,
      start: '2025-09-10',
      end: '2025-09-18',
    },
    {
      id: 'T004',
      projectId: 'P-0001',
      タスク名: '内装仕上げ確認',
      タスク種別: '施工',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-09-20',
      期限: '2025-09-28',
      ['工数見積(h)']: 8,
      start: '2025-09-20',
      end: '2025-09-28',
    },
    // P-0002 タスク
    {
      id: 'T005',
      projectId: 'P-0002',
      タスク名: '現地調査・測量',
      タスク種別: '調査',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-09-01',
      期限: '2025-09-05',
      ['工数見積(h)']: 8,
      ['工数実績(h)']: 8,
      start: '2025-09-01',
      end: '2025-09-05',
      progress: 1,
    },
    {
      id: 'T006',
      projectId: 'P-0002',
      タスク名: '基本設計作成',
      タスク種別: '設計',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-06',
      期限: '2025-09-15',
      ['工数見積(h)']: 24,
      ['工数実績(h)']: 16,
      start: '2025-09-06',
      end: '2025-09-15',
      progress: 0.67,
    },
    {
      id: 'T007',
      projectId: 'P-0002',
      タスク名: '実施設計作成',
      タスク種別: '設計',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-09-16',
      期限: '2025-09-30',
      ['工数見積(h)']: 40,
      start: '2025-09-16',
      end: '2025-09-30',
    },
    {
      id: 'T008',
      projectId: 'P-0002',
      タスク名: '施工業者選定',
      タスク種別: '発注',
      担当者: '田中 太郎',
      assignee: '田中 太郎',
      優先度: '中',
      ステータス: '進行中',
      予定開始日: '2025-09-20',
      期限: '2025-10-05',
      ['工数見積(h)']: 16,
      start: '2025-09-20',
      end: '2025-10-05',
      progress: 0.3,
    },
    {
      id: 'T009',
      projectId: 'P-0002',
      タスク名: '内装工事',
      タスク種別: '施工',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-10',
      期限: '2025-11-05',
      ['工数見積(h)']: 80,
      start: '2025-10-10',
      end: '2025-11-05',
    },
    // P-0003 タスク
    {
      id: 'T010',
      projectId: 'P-0003',
      タスク名: '要件ヒアリング',
      タスク種別: '企画',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-15',
      期限: '2025-09-22',
      ['工数見積(h)']: 12,
      start: '2025-09-15',
      end: '2025-09-22',
      progress: 0.5,
    },
    {
      id: 'T011',
      projectId: 'P-0003',
      タスク名: 'コンセプト設計',
      タスク種別: '設計',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-09-25',
      期限: '2025-10-10',
      ['工数見積(h)']: 32,
      start: '2025-09-25',
      end: '2025-10-10',
    },
    {
      id: 'T012',
      projectId: 'P-0003',
      タスク名: '見積取得',
      タスク種別: '発注',
      担当者: '佐藤 美咲',
      assignee: '佐藤 美咲',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-15',
      期限: '2025-10-25',
      ['工数見積(h)']: 16,
      start: '2025-10-15',
      end: '2025-10-25',
    },
    {
      id: 'T013',
      projectId: 'P-0003',
      タスク名: '詳細設計',
      タスク種別: '設計',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-28',
      期限: '2025-11-20',
      ['工数見積(h)']: 48,
      start: '2025-10-28',
      end: '2025-11-20',
    },
    // P-0004 タスク
    {
      id: 'T014',
      projectId: 'P-0004',
      タスク名: '現地視察',
      タスク種別: '調査',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-01',
      期限: '2025-10-05',
      ['工数見積(h)']: 8,
      start: '2025-10-01',
      end: '2025-10-05',
    },
    {
      id: 'T015',
      projectId: 'P-0004',
      タスク名: 'ゾーニング計画',
      タスク種別: '設計',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-08',
      期限: '2025-10-20',
      ['工数見積(h)']: 24,
      start: '2025-10-08',
      end: '2025-10-20',
    },
    {
      id: 'T016',
      projectId: 'P-0004',
      タスク名: '内装デザイン',
      タスク種別: '設計',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '低',
      ステータス: '未着手',
      予定開始日: '2025-10-25',
      期限: '2025-11-15',
      ['工数見積(h)']: 40,
      start: '2025-10-25',
      end: '2025-11-15',
    },
    // P-0005 タスク
    {
      id: 'T017',
      projectId: 'P-0005',
      タスク名: '躯体工事',
      タスク種別: '施工',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-08-01',
      期限: '2025-08-20',
      ['工数見積(h)']: 120,
      ['工数実績(h)']: 120,
      start: '2025-08-01',
      end: '2025-08-20',
      progress: 1,
    },
    {
      id: 'T018',
      projectId: 'P-0005',
      タスク名: '設備配管工事',
      タスク種別: '施工',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-08-25',
      期限: '2025-09-15',
      ['工数見積(h)']: 80,
      ['工数実績(h)']: 60,
      start: '2025-08-25',
      end: '2025-09-15',
      progress: 0.75,
    },
    {
      id: 'T019',
      projectId: 'P-0005',
      タスク名: '電気配線工事',
      タスク種別: '施工',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-10',
      期限: '2025-09-30',
      ['工数見積(h)']: 60,
      ['工数実績(h)']: 30,
      start: '2025-09-10',
      end: '2025-09-30',
      progress: 0.5,
    },
    {
      id: 'T020',
      projectId: 'P-0005',
      タスク名: '内装仕上げ',
      タスク種別: '施工',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-01',
      期限: '2025-10-20',
      ['工数見積(h)']: 80,
      start: '2025-10-01',
      end: '2025-10-20',
    },
    {
      id: 'T021',
      projectId: 'P-0005',
      タスク名: '検査・引渡し準備',
      タスク種別: '検査',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-22',
      期限: '2025-10-30',
      ['工数見積(h)']: 24,
      start: '2025-10-22',
      end: '2025-10-30',
    },
    // P-0006 タスク（上野駅前 飲食店改装）
    {
      id: 'T022',
      projectId: 'P-0006',
      タスク名: '現地調査・測量',
      タスク種別: '調査',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-09-10',
      期限: '2025-09-12',
      ['工数見積(h)']: 8,
      ['工数実績(h)']: 8,
      start: '2025-09-10',
      end: '2025-09-12',
      progress: 1,
    },
    {
      id: 'T023',
      projectId: 'P-0006',
      タスク名: '厨房レイアウト設計',
      タスク種別: '設計',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-15',
      期限: '2025-09-25',
      ['工数見積(h)']: 32,
      ['工数実績(h)']: 20,
      start: '2025-09-15',
      end: '2025-09-25',
      progress: 0.6,
    },
    {
      id: 'T024',
      projectId: 'P-0006',
      タスク名: '客席エリア設計',
      タスク種別: '設計',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-18',
      期限: '2025-09-30',
      ['工数見積(h)']: 24,
      start: '2025-09-18',
      end: '2025-09-30',
      progress: 0.4,
    },
    {
      id: 'T025',
      projectId: 'P-0006',
      タスク名: '換気設備設計',
      タスク種別: '設備',
      担当者: '中村',
      assignee: '中村',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-01',
      期限: '2025-10-10',
      ['工数見積(h)']: 20,
      start: '2025-10-01',
      end: '2025-10-10',
    },
    {
      id: 'T026',
      projectId: 'P-0006',
      タスク名: '内装工事',
      タスク種別: '施工',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-15',
      期限: '2025-11-10',
      ['工数見積(h)']: 80,
      start: '2025-10-15',
      end: '2025-11-10',
    },
    {
      id: 'T027',
      projectId: 'P-0006',
      タスク名: '厨房機器設置',
      タスク種別: '施工',
      担当者: '田中 太郎',
      assignee: '田中 太郎',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-11-12',
      期限: '2025-11-20',
      ['工数見積(h)']: 24,
      start: '2025-11-12',
      end: '2025-11-20',
    },
    // P-0007 タスク（六本木ヒルズ オフィス移転）
    {
      id: 'T028',
      projectId: 'P-0007',
      タスク名: '移転要件ヒアリング',
      タスク種別: '企画',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-10-01',
      期限: '2025-10-10',
      ['工数見積(h)']: 16,
      start: '2025-10-01',
      end: '2025-10-10',
      progress: 0.3,
    },
    {
      id: 'T029',
      projectId: 'P-0007',
      タスク名: 'スペースプランニング',
      タスク種別: '設計',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-15',
      期限: '2025-11-05',
      ['工数見積(h)']: 40,
      start: '2025-10-15',
      end: '2025-11-05',
    },
    {
      id: 'T030',
      projectId: 'P-0007',
      タスク名: 'ネットワーク設計',
      タスク種別: '設備',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-11-10',
      期限: '2025-11-25',
      ['工数見積(h)']: 32,
      start: '2025-11-10',
      end: '2025-11-25',
    },
    {
      id: 'T031',
      projectId: 'P-0007',
      タスク名: 'オフィス家具選定',
      タスク種別: '発注',
      担当者: '佐藤 美咲',
      assignee: '佐藤 美咲',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-11-20',
      期限: '2025-12-10',
      ['工数見積(h)']: 24,
      start: '2025-11-20',
      end: '2025-12-10',
    },
    {
      id: 'T032',
      projectId: 'P-0007',
      タスク名: '内装工事',
      タスク種別: '施工',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-12-15',
      期限: '2026-01-31',
      ['工数見積(h)']: 120,
      start: '2025-12-15',
      end: '2026-01-31',
    },
    {
      id: 'T033',
      projectId: 'P-0007',
      タスク名: '移転作業・引渡し',
      タスク種別: '施工',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2026-02-10',
      期限: '2026-02-25',
      ['工数見積(h)']: 40,
      start: '2026-02-10',
      end: '2026-02-25',
    },
    // P-0008 タスク（銀座中央通り ブティック新装）
    {
      id: 'T034',
      projectId: 'P-0008',
      タスク名: '現地調査',
      タスク種別: '調査',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-08-15',
      期限: '2025-08-18',
      ['工数見積(h)']: 8,
      ['工数実績(h)']: 8,
      start: '2025-08-15',
      end: '2025-08-18',
      progress: 1,
    },
    {
      id: 'T035',
      projectId: 'P-0008',
      タスク名: 'デザインコンセプト',
      タスク種別: '設計',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-08-20',
      期限: '2025-08-30',
      ['工数見積(h)']: 32,
      ['工数実績(h)']: 32,
      start: '2025-08-20',
      end: '2025-08-30',
      progress: 1,
    },
    {
      id: 'T036',
      projectId: 'P-0008',
      タスク名: '照明設計',
      タスク種別: '設備',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-01',
      期限: '2025-09-10',
      ['工数見積(h)']: 20,
      ['工数実績(h)']: 15,
      start: '2025-09-01',
      end: '2025-09-10',
      progress: 0.75,
    },
    {
      id: 'T037',
      projectId: 'P-0008',
      タスク名: 'ディスプレイ什器製作',
      タスク種別: '発注',
      担当者: '佐藤 美咲',
      assignee: '佐藤 美咲',
      優先度: '中',
      ステータス: '進行中',
      予定開始日: '2025-09-05',
      期限: '2025-09-20',
      ['工数見積(h)']: 24,
      start: '2025-09-05',
      end: '2025-09-20',
      progress: 0.5,
    },
    {
      id: 'T038',
      projectId: 'P-0008',
      タスク名: '内装仕上げ工事',
      タスク種別: '施工',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-09-22',
      期限: '2025-10-05',
      ['工数見積(h)']: 60,
      start: '2025-09-22',
      end: '2025-10-05',
    },
    {
      id: 'T039',
      projectId: 'P-0008',
      タスク名: '商品陳列・引渡し',
      タスク種別: '施工',
      担当者: '田中 太郎',
      assignee: '田中 太郎',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-08',
      期限: '2025-10-12',
      ['工数見積(h)']: 16,
      start: '2025-10-08',
      end: '2025-10-12',
    },
    // P-0009 タスク（恵比寿ガーデン クリニック）
    {
      id: 'T040',
      projectId: 'P-0009',
      タスク名: '現地調査・要件確認',
      タスク種別: '調査',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-09-20',
      期限: '2025-09-25',
      ['工数見積(h)']: 12,
      ['工数実績(h)']: 12,
      start: '2025-09-20',
      end: '2025-09-25',
      progress: 1,
    },
    {
      id: 'T041',
      projectId: 'P-0009',
      タスク名: '診察室レイアウト設計',
      タスク種別: '設計',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-28',
      期限: '2025-10-15',
      ['工数見積(h)']: 40,
      start: '2025-09-28',
      end: '2025-10-15',
      progress: 0.4,
    },
    {
      id: 'T042',
      projectId: 'P-0009',
      タスク名: '医療設備設計',
      タスク種別: '設備',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-18',
      期限: '2025-11-05',
      ['工数見積(h)']: 48,
      start: '2025-10-18',
      end: '2025-11-05',
    },
    {
      id: 'T043',
      projectId: 'P-0009',
      タスク名: '待合室設計',
      タスク種別: '設計',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-20',
      期限: '2025-11-01',
      ['工数見積(h)']: 24,
      start: '2025-10-20',
      end: '2025-11-01',
    },
    {
      id: 'T044',
      projectId: 'P-0009',
      タスク名: '内装工事',
      タスク種別: '施工',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-11-10',
      期限: '2025-12-10',
      ['工数見積(h)']: 100,
      start: '2025-11-10',
      end: '2025-12-10',
    },
    {
      id: 'T045',
      projectId: 'P-0009',
      タスク名: '医療機器設置',
      タスク種別: '施工',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-12-12',
      期限: '2025-12-20',
      ['工数見積(h)']: 32,
      start: '2025-12-12',
      end: '2025-12-20',
    },
    // P-0010 タスク（秋葉原駅前 ゲームセンター）
    {
      id: 'T046',
      projectId: 'P-0010',
      タスク名: '現地調査',
      タスク種別: '調査',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-15',
      期限: '2025-10-20',
      ['工数見積(h)']: 12,
      start: '2025-10-15',
      end: '2025-10-20',
    },
    {
      id: 'T047',
      projectId: 'P-0010',
      タスク名: 'フロアプランニング',
      タスク種別: '設計',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-10-25',
      期限: '2025-11-15',
      ['工数見積(h)']: 48,
      start: '2025-10-25',
      end: '2025-11-15',
    },
    {
      id: 'T048',
      projectId: 'P-0010',
      タスク名: '電気設備設計',
      タスク種別: '設備',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-11-18',
      期限: '2025-12-05',
      ['工数見積(h)']: 40,
      start: '2025-11-18',
      end: '2025-12-05',
    },
    {
      id: 'T049',
      projectId: 'P-0010',
      タスク名: '音響・照明設計',
      タスク種別: '設備',
      担当者: '中村',
      assignee: '中村',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2025-11-20',
      期限: '2025-12-10',
      ['工数見積(h)']: 32,
      start: '2025-11-20',
      end: '2025-12-10',
    },
    {
      id: 'T050',
      projectId: 'P-0010',
      タスク名: 'ゲーム機配置設計',
      タスク種別: '設計',
      担当者: '佐藤 美咲',
      assignee: '佐藤 美咲',
      優先度: '低',
      ステータス: '未着手',
      予定開始日: '2025-12-15',
      期限: '2026-01-10',
      ['工数見積(h)']: 40,
      start: '2025-12-15',
      end: '2026-01-10',
    },
    {
      id: 'T051',
      projectId: 'P-0010',
      タスク名: '内装工事',
      タスク種別: '施工',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2026-01-15',
      期限: '2026-03-01',
      ['工数見積(h)']: 160,
      start: '2026-01-15',
      end: '2026-03-01',
    },
    {
      id: 'T052',
      projectId: 'P-0010',
      タスク名: 'ゲーム機設置・調整',
      タスク種別: '施工',
      担当者: '田中 太郎',
      assignee: '田中 太郎',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2026-03-05',
      期限: '2026-03-20',
      ['工数見積(h)']: 48,
      start: '2026-03-05',
      end: '2026-03-20',
    },
    // マイルストーンタスク
    // P-0001 マイルストーン
    {
      id: 'M001',
      projectId: 'P-0001',
      タスク名: '設計承認',
      タスク種別: 'マイルストーン',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-09-12',
      期限: '2025-09-12',
      start: '2025-09-12',
      end: '2025-09-12',
      milestone: true,
    },
    {
      id: 'M002',
      projectId: 'P-0001',
      タスク名: '工事完了検査',
      タスク種別: 'マイルストーン',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-01',
      期限: '2025-10-01',
      start: '2025-10-01',
      end: '2025-10-01',
      milestone: true,
    },
    // P-0002 マイルストーン
    {
      id: 'M003',
      projectId: 'P-0002',
      タスク名: 'クライアント最終確認',
      タスク種別: 'マイルストーン',
      担当者: '田中 太郎',
      assignee: '田中 太郎',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-01',
      期限: '2025-10-01',
      start: '2025-10-01',
      end: '2025-10-01',
      milestone: true,
    },
    {
      id: 'M004',
      projectId: 'P-0002',
      タスク名: 'オープン準備完了',
      タスク種別: 'マイルストーン',
      担当者: '山田 次郎',
      assignee: '山田 次郎',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-11-10',
      期限: '2025-11-10',
      start: '2025-11-10',
      end: '2025-11-10',
      milestone: true,
    },
    // P-0003 マイルストーン
    {
      id: 'M005',
      projectId: 'P-0003',
      タスク名: '企画承認',
      タスク種別: 'マイルストーン',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '進行中',
      予定開始日: '2025-09-22',
      期限: '2025-09-22',
      start: '2025-09-22',
      end: '2025-09-22',
      milestone: true,
      progress: 0.8,
    },
    // P-0005 マイルストーン
    {
      id: 'M006',
      projectId: 'P-0005',
      タスク名: '躯体検査完了',
      タスク種別: 'マイルストーン',
      担当者: '中村',
      assignee: '中村',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-08-20',
      期限: '2025-08-20',
      start: '2025-08-20',
      end: '2025-08-20',
      milestone: true,
      progress: 1,
    },
    {
      id: 'M007',
      projectId: 'P-0005',
      タスク名: '設備検査',
      タスク種別: 'マイルストーン',
      担当者: '高橋 健一',
      assignee: '高橋 健一',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-01',
      期限: '2025-10-01',
      start: '2025-10-01',
      end: '2025-10-01',
      milestone: true,
    },
    // P-0006 マイルストーン
    {
      id: 'M008',
      projectId: 'P-0006',
      タスク名: '保健所検査',
      タスク種別: 'マイルストーン',
      担当者: '木村 健太',
      assignee: '木村 健太',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-11-20',
      期限: '2025-11-20',
      start: '2025-11-20',
      end: '2025-11-20',
      milestone: true,
    },
    // P-0008 マイルストーン
    {
      id: 'M009',
      projectId: 'P-0008',
      タスク名: 'デザイン最終確認',
      タスク種別: 'マイルストーン',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '高',
      ステータス: '完了',
      予定開始日: '2025-08-30',
      期限: '2025-08-30',
      start: '2025-08-30',
      end: '2025-08-30',
      milestone: true,
      progress: 1,
    },
    {
      id: 'M010',
      projectId: 'P-0008',
      タスク名: 'グランドオープン',
      タスク種別: 'マイルストーン',
      担当者: '小林 真理',
      assignee: '小林 真理',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-10-15',
      期限: '2025-10-15',
      start: '2025-10-15',
      end: '2025-10-15',
      milestone: true,
    },
    // P-0009 マイルストーン
    {
      id: 'M011',
      projectId: 'P-0009',
      タスク名: '医療機器検査',
      タスク種別: 'マイルストーン',
      担当者: '加藤 誠',
      assignee: '加藤 誠',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2025-12-22',
      期限: '2025-12-22',
      start: '2025-12-22',
      end: '2025-12-22',
      milestone: true,
    },
    // P-0010 マイルストーン
    {
      id: 'M012',
      projectId: 'P-0010',
      タスク名: '消防検査',
      タスク種別: 'マイルストーン',
      担当者: '斉藤 大輔',
      assignee: '斉藤 大輔',
      優先度: '高',
      ステータス: '未着手',
      予定開始日: '2026-03-15',
      期限: '2026-03-15',
      start: '2026-03-15',
      end: '2026-03-15',
      milestone: true,
    },
    {
      id: 'M013',
      projectId: 'P-0010',
      タスク名: 'プレオープン',
      タスク種別: 'マイルストーン',
      担当者: '櫻本 聖成',
      assignee: '櫻本 聖成',
      優先度: '中',
      ステータス: '未着手',
      予定開始日: '2026-03-25',
      期限: '2026-03-25',
      start: '2026-03-25',
      end: '2026-03-25',
      milestone: true,
    },
  ],
  people: [
    { id: 'PERSON001', 氏名: '櫻本 聖成', 役割: 'PM/設計統括', メール: 's.sakuramoto@archi-prisma.co.jp' },
    { id: 'PERSON002', 氏名: '中村', 役割: '管理建築士/設計', メール: 's.nakamura@archi-prisma.co.jp' },
    { id: 'PERSON003', 氏名: '山田 次郎', 役割: '設計/施工管理', メール: 'j.yamada@archi-prisma.co.jp' },
    { id: 'PERSON004', 氏名: '高橋 健一', 役割: '設備設計', メール: 'k.takahashi@archi-prisma.co.jp' },
    { id: 'PERSON005', 氏名: '田中 太郎', 役割: '営業/発注管理', メール: 't.tanaka@archi-prisma.co.jp' },
    { id: 'PERSON006', 氏名: '佐藤 美咲', 役割: 'コーディネーター', メール: 'm.sato@archi-prisma.co.jp' },
  ],
};
